### PR TITLE
Design refresh with animated character sprites

### PR DESCRIPTION
**Pull request by niamu**
I had some spare time on my hands and thought I'd do a small design refresh on the site.

It has some tiny animation flares including all dancing character sprites on the characters.html page. The colours used across the design are now all sampled from the background or the logo and finally it is all responsive.

I've updated the README to make it easier to understand how to build the project to test things locally as well.

projecthawkthorne

### CODE REVIEW

**Comment by kyleconroy** [comment]
Incredible! I sadly won’t have a chance to review this until Monday. Thanks
for the changes.

**Comment by kyleconroy** [comment]
The new characters page looks great. 

I dig the new animation, but find it distracting that it fades in on every page load. Would it be possible to only do the fade in animation on the main page? For the other pages, have the sparkles, but no slide and no fade.

**Review by kyleconroy — CHANGES_REQUESTED** [review]
The new characters page looks great.

I dig the new animation, but find it distracting that it fades in on every page load. Would it be possible to only do the fade in animation on the main page? For the other pages, have the sparkles, but no slide and no fade.

**Comment by niamu** [comment]
Absolutely. I'll get those changes done soon.

I was also considering building a little more extensive character page in another iteration to replace the broken [hawkthorne-costume](/hawkthorne/hawkthorne-costume) project. What do you think?

**Comment by kyleconroy** [comment]
I miss the costume project, so I’d love to have it again. Let’s save that
for another PR?

**Comment by niamu** [comment]
Yeah, I won't get to that for a few more days at best anyways, so it will definitely be another PR.

**Comment by kyleconroy** [comment]
hahah of course

**Review by kyleconroy — APPROVED** [review]

**Pull request merged**
